//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace almany
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfterBeforeImage
    {
        public int id { get; set; }
        public string url_picture_before { get; set; }
        public string url_picture_after { get; set; }
        public Nullable<bool> statuss { get; set; }
        public string first_title { get; set; }
        public string secoundry_title { get; set; }
    }
}
